### ISSUE TITLE
Output as a single file (to avoid needing to run a webserver to view model)

### ISSUE THREAD

**Issue by luzpaz** [X-Ryl669/freecadWebExport#2]
Per the README, the only limitation beside using 3rd party software to convert to the gITF format (which has been implemented in upstream (https://github.com/X-Ryl669/freecadWebExport/issues/1#issuecomment-731763808) is:

> Currently, it's not a single document file (but it can be, with some work) so you need to serve the output folder/archive via a webserver.

**Comment by X-Ryl669** [comment]
I already did this for my Docsify plugin [here](https://github.com/X-Ryl669/docsify-gltfexplorer). There are 2 files (the "player" and the GLTF file). In order to make it a single file, that would require embedding the GLTF in the HTML file, it's possible by appending a `<template>` tag with the GLTF embedded file as JSON. This will works as long as there isn't any external texture (since GLTF is a JSON format, so it links the external textures instead of embedding them). However, the "source" file will not validate since it won't have a closing `<html>` tag.

**Comment by X-Ryl669** [comment]
Please check the **singleFile** branch for an implementation of a single HTML file output. It consists in concatenating the player (called `top.html`), your GLTF file and the footer (called `end.html`). 
This 3 part design is required for a valid HTML5 file. It's possible to generate a 2 part design, but we won't have closing tags so it won't validate (but all browser I know of will accept it anyway).

I hope some FreeCAD developer can see this and implement this in FreeCAD it would be very cool! In python, one only has to store the template player and replace the part between the `script` tag with the actual GLTF file content.

It can also be stored in binary if converted to base64 beforehand to reduce the size of the output file (convenient for distribution via email for example).

**Comment by luzpaz** [comment]
Can you share this in the [Open DIscussion subforum](https://forum.freecadweb.org/viewforum.php?f=8). I'm sure we can get interest and potentially traction around this

**Comment by X-Ryl669** [comment]
[Done](https://forum.freecadweb.org/viewtopic.php?f=8&t=31680&start=20). Hope it'll be accepted ;-)
